services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dosbox-pure
    environment:
      SKIP_SOURCE_UPDATE: "1"
    volumes:
      - ./output:/build/output
      - ./compile:/build/compile
      - ./patches:/build/patches:ro
      - ../dosbox-pure:/source/dosbox-pure
